
type UserList {
  total: Int,
  results: [User]
}

type User {
  id: ID!
  username: String
  email: String
  authtoken: String
  active: Boolean
  avatar: String
  roles: [RoleUser]
}

type File {
  filename: String!
  mimetype: String!
  encoding: String!
}
