
createRole(
  label: String!
  system: String!
): Role

updateRole(
  id: ID!
  label: String!
  system: String!
): Role

updatePermission(
  id: ID!
  resource: String!
  role_id: ID!
  access: Boolean!
): Permission

updateRoleHook(
  id: ID!
  hook: String!
  role_id: ID!
  bypass: Boolean!
): Boolean

updateRoleUser(
  id: ID!
  user_id: ID!
  role_id: ID!
  active: Boolean!
): Boolean
